### ISSUE TITLE
SwiftUI Example WaveformLiveView

### ISSUE THREAD

**Issue by MostafaALZOUBI1994** [dmrschmidt/DSWaveformImage#36]
please provide  WaveformLiveView for swiftui from audio recorder

**Comment by dmrschmidt** [comment]
In the current form, that would look almost identical to https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImageExample/SwiftUIExample/WaveformImageViewUI.swift only that you'd need to adapt everything to handle a `let samples: [Float]` instead of the `let audioURL: URL`.

You may want to familiarize yourself with the workings of [UIViewRepresentable](https://developer.apple.com/documentation/swiftui/uiviewrepresentable).

I'm planning on building a more native SwiftUI implementation for performance reasons for the live view, which is why I am intentionally not including this in the repository directly.

**Comment by dmrschmidt** [comment]
FYI, there is now a native SwiftUI live view: https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImage/DSWaveformImage/SwiftUI/WaveformLiveCanvas.swift
