### ISSUE TITLE
Render bug?

### ISSUE THREAD

**Issue by predam** [dmrschmidt/DSWaveformImage#41]
Hello, any idea why this happen?

![RPReplay_Final1662818646](https://user-images.githubusercontent.com/9632910/189488816-0780bf34-000d-4df2-a835-42ba0033e360.gif)

I am using SwiftUI, and I wrapped the wave view into UIViewRepresentable. 
The configuration of WaveformLiveView:

```swift
let configuration: Waveform.Configuration = Waveform.Configuration(
            style: .striped(.init(color: .red, width: 3, spacing: 3)),
            dampening: .init(percentage: 0.2, sides: .both),
            position: .middle,
            verticalScalingFactor: 2,
            shouldAntialias: true
        )
```

**Comment by dmrschmidt** [comment]
Hey @predam, without more context, this is tough to tell.

From afar, it looks like the view is not re-rendering itself and instead rendering a new view every time, while leaving the old one in place. That would explain why over time it renders completely opaque red.

So my wild guess is that either your implementation of `UIViewRepresentable` isn't quite right and leaves "dead views" all over the place, or the code embedding that wrapped view is doing something funky.

If this is true, you should likely also be able to observe the memory usage of your app go up continuously (possibly slowly, but still ever-increasing until it would run out of memory).

Let me know if this hints you in the right direction.

**Comment by predam** [comment]
I can't figure out what I'm doing wrong.

Here is my code

```swift
struct ContentView: View {
    private let audio = AudioRecorder()
    private let liveView = WaveformLiveView()
    private let timer = Timer.publish(every: 0.01, on: .main, in: .common).autoconnect()
    
    var body: some View {
        VStack {
            AudioLiveView(liveView: liveView)
            Spacer()
            Button("toggle"){
                if audio.recording{
                    audio.stopRecording()
                } else {
                    audio.startRecording()
                   
                }
            }.onReceive(timer) { _ in
                if(audio.recording) {
                    let value = audio.getMeteredValue()
                    liveView.add(sample: value)
                }
            }
        }
        .padding();
    }
   
}

struct AudioLiveView: UIViewRepresentable {
    var liveView: WaveformLiveView
    

    func makeUIView(context: Context) -> WaveformLiveView {

        let configuration: Waveform.Configuration = Waveform.Configuration(
            style: .striped(.init(color: .red, width: 3, spacing: 3)),
            dampening: .init(percentage: 0.2, sides: .both),
            position: .middle,
            verticalScalingFactor: 2,
            shouldAntialias: true
        )

        liveView.configuration = configuration
        return liveView
    }
    
    func updateUIView(_ uiView: WaveformLiveView, context: Context) {
       //
    }
    
  }
```

**Comment by dmrschmidt** [comment]
I did not run this code, so this is again just me doing an educated guess from reading through it.

I think the issue may just be what I had speculated earlier: your implementation of UIViewRepresentable and what looks like a misunderstanding of SwiftUI principles. Let me explain:

Have a look at the [example implementation of using UIViewRepresentable](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImageExample/SwiftUIExample/WaveformImageViewUI.swift#L19), most importantly the highlighted line.

What you'll notice is, that the underlying UIKit view is instantiated there. T**his is the important detail.** Each UIViewRepresentable implementation should **own** its managed view. Your implementation however passes in that view and instead instantiates it in `private let liveView = WaveformLiveView()`.

The other tricky piece here now is where the misunderstanding of SwiftUI comes in. A SwiftUI view - the struct that is - is more like a representation rather than the actual view itself. A new struct is instantiated by SwiftUI every time any update to the view occurs. So you may end up instantiating thousands of `WaveformLiveView` within a short amount of time.

If you follow the approach of the example project more closely, you should be successful.

I recommend you watch [https://developer.apple.com/videos/play/wwdc2020/10040/](https://developer.apple.com/videos/play/wwdc2020/10040/) and [Demystify SwiftUI](https://developer.apple.com/videos/play/wwdc2021/10022) to get a better understanding of SwiftUI's internals.

**Comment by dmrschmidt** [comment]
I should add that, all this said, `WaveformLiveView` does not lend itself well very well to simply be wrapped inside a UIViewRepresentable in a simplistic way due to its API, which is very UIKit-imperative. I.e. you wouldn't have an `addSamples` method in a SwiftUI view ever to pass data to it. So you'd definitely need some more complex wrapper.

I am still planning on writing a native SwiftUI implementation because of that.

**Comment by dmrschmidt** [comment]
Me again :)

I've used a current down time I'm having to take another stab at creating a native SwiftUI version of the live view.

There's a preliminary draft of this now on main: https://github.com/dmrschmidt/DSWaveformImage/commit/02578315aa119747e9aeba58a39c4174be61d6a7

Depending on your needs, you could just check out main and use the new [WaveformLiveCanvas](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImage/DSWaveformImage/WaveformLiveCanvas.swift). I'm not expecting it to change much in terms of API, so any changes needed once this becomes a proper release in the next few days will be trivial.

There's also [example code](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImageExample/SwiftUIExample/SwiftUIExampleView.swift) which illustrates how it should be used with an audio recorder. Referencing back to what I wrote earlier, one thing to take note of there is the use of it as a @StateObject, to prevent the issues of constantly re-allocating new instances thousands of times per second as in your original code snippet.

The only thing really left to do until this is 100% release ready is some annoying flickering issue in some instances when choosing the striped style.

**Comment by dmrschmidt** [comment]
The last remaining issue has been fixed and there's a new official [Release 10.1.0](https://github.com/dmrschmidt/DSWaveformImage/releases/tag/10.1.0) with a [native SwiftUI live rendering view](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImage/DSWaveformImage/SwiftUI/WaveformLiveCanvas.swift).

**Comment by predam** [comment]
Thank you, @dmrschmidt 🙏. I am new to the swift world, so thank you for the resources.

**Comment by Akazm** [comment]
I'm nevertheless experiencing the same issue, but when using `WaveFormLiveView`. The view appears to be always using the latest highest volume peak while also drawing 'over itself'.

https://github.com/dmrschmidt/DSWaveformImage/assets/37962180/c68b3261-3e22-45d0-9a7f-765c6fd0a642

**Comment by dmrschmidt** [comment]
Hey @Akazm would you mind sharing some code context in which the view is used?

Generally speaking:
* use `WaveformLiveView` in a pure UIKit context.
* use `WaveformLiveCanvas` in a pure SwiftUI context

**Comment by Akazm** [comment]
Hi, it's a mixed context, although my SwiftUI view and the WaveFormLiveView were both nested on the same hierarchy level within an UIView.

Nevertheless - my approach was purely programmatically. It works when using a storyboard, so I assume (?!) it's either a constraint issue (although nothing fancy happened, didn't touch any nested views) or an initializer issue.

**Comment by dmrschmidt** [comment]
Mixed context does sound like this might be the issue then. You want to ensure that `WaveFormLiveView` does not have any SwiftUI ancestors. It's immediate parent must be a UIKit view, and so must all of that view's ancestors.

If you do have any SwiftUI ancestors which embed a UIKit parent anywhere in this hierarchy, that could lead to the issue you are experiencing. Which is a result of the different lifecycle methods.

The library does not support a mixed use case. It has two different native views, which achieve the same results respectively.

Without your code - and in this case your exact view hierarchy - I won't be able to help more, other than advising you to ensure you use the correct choice of either `WaveformLiveView` or `WaveformLiveCanvas` depending on the scenario.

My **guess** is, you might be better off adapting your view hierarchy so you can cleanly use `WaveformLiveCanvas` inside a SwiftUI context.

**Comment by Akazm** [comment]
> Mixed context does sound like this might be the issue then. You want to ensure that WaveFormLiveView does not have any SwiftUI ancestors, ie is never wrapped as a UIViewRepresentable anywhere in its ancestry chain.

Oh, they aren't, the live view from the video above is just next to a SwiftUI view, both sharing a common UIKit ancestor.

**Comment by adamwulf** [comment]
For anyone else that found this thread because the UIKit WaveFormLiveView was showing render issues even in a pure UIKit setting, I was able to fix it by:

``` swift
        waveformView.clearsContextBeforeDrawing = true
        waveformView.isOpaque = true
        waveformView.backgroundColor = .black // could be any color
```

or

``` swift
        waveformView.clearsContextBeforeDrawing = true
        waveformView.isOpaque = false
        waveformView.backgroundColor = .clear
```

but not

``` swift
        waveformView.clearsContextBeforeDrawing = true   // UIKit default
        waveformView.isOpaque = true                     // UIKit default
        waveformView.backgroundColor = nil               // UIKit default
```

The sneaky bit [in the docs for](https://developer.apple.com/documentation/uikit/uiview/1622449-clearscontextbeforedrawing) `clearsContextBeforeDrawing` is:

> If the view’s isOpaque property is also set to true, the backgroundColor property of the view must not be nil or drawing errors may occur.

This happens if you init the `WaveformLiveView` in code, as the UIKit defaults for UIView would cause this rendering bug to appear. This does not happen in the demo app because it is configured in a storyboard.

And, of course, thank you @dmrschmidt for your amazing library!

**Comment by dmrschmidt** [comment]
Hey @adamwulf, thanks for writing this. So, if I get this right, then the library would ideally set a more sensible default for itself when `init` in code, right? And that would probably be the 2nd example from your post, assuming that most people would want the background to be clear.
