### ISSUE TITLE
return NSImage instead of view

### ISSUE THREAD

**Issue by Necrospasm** [dmrschmidt/DSWaveformImage#49]
Hi,

Try as I might (I'm still fairly new to swiftui), I couldn't manage to return the generated waveform instead of just displaying it. The goal I'm trying to achieve is this that I get a returned NSImage of the generated image so that I can store that data (.tiffRepresentation). Is there anyway this package can do that? I tried hacking about the code for about 2 days now with no success. Any help is appreciated. Thank you.

**Comment by dmrschmidt** [comment]
Hey @Necrospasm, it sounds like you may be not be using `WaveformImageDrawer` directly.

Please refer to this example here:
https://github.com/dmrschmidt/DSWaveformImage#waveformimagedrawer---creates-a-uiimage-waveform-from-an-audio-file

On macOS, it'll create an `NSImage` instead of a `UIImage`.

If you run into problems with this approach, please let me know with the specifics and I can try to help :)

**Comment by Necrospasm** [comment]
Hello @dmrschmidt, thanks for your reply. I did try that example before but for some reason it's not working for me. It's returning blank or errors out that the image is nil.

This is the code that I'm using : 

```
let waveformImageDrawer = WaveformImageDrawer()
waveformImageDrawer.waveformImage(fromAudioAt: URL(fileURLWithPath: filenamePath), with: .init(
                                  size: NSSize(width: 80, height: 45),
                                  style: .filled(NSColor.black),
                                  position: .top)) { image in
    // need to jump back to main queue
    DispatchQueue.main.async {
        appData.generatedThumbnail = (image?.tiffRepresentation)!
    }
}
```

I tried various variations of the above code. I essentially don't need to push the image to a view to be displayed but to assign it to a data variable (@Published var generatedThumbnail = Data()) so that I can save the image to a db blob (I know it's not the best approach but to my defence, it's just an 80x45 :P ) instead via a function DBManager.shared.addMedia(mediaThumbnail: appData.generatedThumbnail)

**Comment by dmrschmidt** [comment]
Since native macOS support was only added recently, I just double checked that this code really works on macOS in the latest version. And it does work for me in the example app.

So let's try debugging this step by step.

* If you check out this repo, try and run the macOS example app.
* Once that works, open the [`ContentView`]()
* replace its `body` with the following code

```swift
    @State var image: NSImage?

    var body: some View {
        VStack {
            if let image {
                Image(nsImage: image)
            } else {
                Text("no image")
            }
        }.onAppear {
            let waveformImageDrawer = WaveformImageDrawer()
            waveformImageDrawer.waveformImage(fromAudioAt: audioURL, with: .init(
                                              size: NSSize(width: 80, height: 45),
                                              style: .filled(NSColor.black),
                                              position: .top)) { img in
                // need to jump back to main queue
                DispatchQueue.main.async {
                    self.image = img
                }
            }
        }
    }
```

That should give you this exact result:

<img width="192" alt="Screenshot 2022-11-21 at 22 13 23" src="https://user-images.githubusercontent.com/69365/203159344-461ee248-2866-419c-a0bf-4114a38740b0.png">

Once you have that working, replace the audio file with the one you are trying to use. If that still results in nothing drawing, let's take it from there.

**Comment by Necrospasm** [comment]
Your code worked and that got me thinking why it wasn't working in my project as the code is for the most part identical. So I created a new view, pasted your code and worked too. Then after about an hour scratching my head, I changed this line :

@Published var generatedThumbnail = Data()
- to -
@Published var generatedThumbnail: Data = Data()

and it worked. Not sure why though but maybe it will help someone else too. Thank you so much for your help mate this is an awesome project.
