### ISSUE TITLE
Why can't I use RecordingDelegate for my own AudioRecorder?

### ISSUE THREAD

**Issue by Medef** [dmrschmidt/DSWaveformImage#53]
Hi! I can't inherit from RecordingDelegate and I can't access SCAudioManager. I'm trying to use WaveformLiveCanvas with samples, but I can't figure out how this is implemented in example of yours. At the moment I have this implementation, but it doesn't quite work correctly
Thank you in advance for your help!
![Снимок экрана 2022-12-15 в 16 52 17](https://user-images.githubusercontent.com/40383119/207876086-a6dfae3f-9724-4b09-b7bf-040a90160394.png)

**Comment by dmrschmidt** [comment]
That’s correct. It’s not part of the library itself, as that’s out of scope. It’s just there for illustration purposes.

You can of course copy & paste the code from the example app if you like to use it as a starting point in your app.

Cheers,
Dennis

**Comment by Medef** [comment]
Thank you for your reply. Please tell me, what time interval do you use in your manager? As far as I understand the interval is 0.1 and 3 identical 'linear' values are added to the array. At the moment I have the problem that the wave is constantly changing, when using WaveformLiveCanvas like this

https://user-images.githubusercontent.com/40383119/208052169-327c135e-0275-487e-a163-c1f9497aec67.mov

**Comment by dmrschmidt** [comment]
Hey @Medef,

that's interesting... Looks like some offset calculations are getting out of sync. Have you tried using

https://github.com/dmrschmidt/DSWaveformImage/blob/main/Example/DSWaveformImageExample-iOS/SwiftUIExample/SwiftUIExampleView.swift

for comparison? That's basically the same UI element you built. I didn't notice the same issue there. Would you mind trying that out?

Regarding the question, yeah the [audio recording is asking iOS for an update every 0.01s](https://github.com/dmrschmidt/DSWaveformImage/blob/73d69a3e4f8b3988494c4cdd2e270baaea183ec0/Example/DSWaveformImageExample-iOS/SCAudioManager.m#L68). That's not really happening in my experience though, so I triple the value we are getting to make the form scroll a little faster. It didn't "feel" right otherwise.

**Comment by Medef** [comment]
I had the interval set to 0.1 and there was distortion because of this. Now I set the interval to 0.01 and it works correctly. I can attach my manager, if someone needs as an example

Thank you for your help, I am very grateful for such quick and timely answers

Best wishes, Eugene

**Comment by Medef** [comment]
Hey, @dmrschmidt 
I had the interval set to 0.1 and there was distortion because of this. Now I set the interval to 0.01 and it works correctly. I can attach my manager, if someone needs as an example

Thank you for your help, I am very grateful for such quick and timely answers

Best wishes, Eugene
[AudioRecorder.swift.zip](https://github.com/dmrschmidt/DSWaveformImage/files/10244197/AudioRecorder.swift.zip)

**Comment by ducduy20** [comment]
Hey @Medef 
Can you give me the code that you can use this record in View?

**Comment by Medef** [comment]
Hey @ducduy20
What exactly are you interested in?
